### ISSUE TITLE
Craft 4 support

### ISSUE THREAD

**Issue by angieherrera** [jalendport/craft-lockout#3]
Hey Jalen! Wondering if this plugin will get updated for Craft 4?

**Comment by jalendport** [comment]
Hey Angie! Yes, I'm planning on updating this plugin for Craft 4. It's not as high on my priority list as Preparse, but I'm planning on trying to get it done in the next month or so... I think you might be the only other person besides myself/Steadfast who uses it 😂

**Comment by wunderbaresnet** [comment]
Well, I am... Thankfully.

**Comment by jalendport** [comment]
Here's an update on where things are at: https://twitter.com/jalendport/status/1628813156888809475

**Comment by jalendport** [comment]
Version [2.0.0](https://github.com/jalendport/craft-lockout/releases/tag/2.0.0) was just released with Craft 4 support 🙃
